cfg_file: 'local_configs/segformer/polyp/patchformer_polyp_moe_2_strct.py'
seed: 0
fold: 0

dataset: polyp

lr: 0.0001
end_lr: 0.00001
epochs: 500
max_decay_epochs: 500
use_mmcv_optim: False
optim_type: adam