cfg_file: 'local_configs/unet/transunet_kvasir.py'
seed: 0
fold: 0

baseline_model: transunet
dataset: kvasir
n_classes: 1
n_channels: 3
trans_Unet: 'R50-ViT-B_16'


lr: 0.01
end_lr: 0.0001
epochs: 500
max_decay_epochs: 500
