cfg_file: 'local_configs/segformer/ours/patchformer_32_32_32_32_aug256_07_2_unethead.py'
seed: 0
fold: 0

dataset: stroke

lr: 0.01
end_lr: 0.0001
epochs: 500
max_decay_epochs: 500
use_mmcv_optim: True